apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: most-monitoring-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/jpradoar/MOSt.git'
    path: .
    targetRevision: main
    directory:
      recurse: true
      jsonnet: {}
  destination: 
    server: 'https://kubernetes.default.svc'
