apiVersion: v1
data:
  prometheus-additional.yaml: IwojIGt1YmVjdGwgY3JlYXRlIHNlY3JldCBnZW5lcmljIGFkZGl0aW9uYWwtc2NyYXBlLWNvbmZpZ3MgLS1mcm9tLWZpbGU9cHJvbWV0aGV1cy1hZGRpdGlvbmFsLnlhbWwgLS1kcnktcnVuPWNsaWVudCAtbiBtb25pdG9yaW5nIC1veWFtbCA+IGFkZGl0aW9uYWwtc2NyYXBlLWNvbmZpZ3MueWFtbAojIGt1YmVjdGwgYXBwbHkgLWYgYWRkaXRpb25hbC1zY3JhcGUtY29uZmlncy55YW1sIC1uIG1vbml0b3JpbmcgCiMga3ViZWN0bCAtbiBtb25pdG9yaW5nIHBvcnQtZm9yd2FyZCBzdmMvcHJvbWV0aGV1cy1rOHMgOTA5MDo5MDkwCiMgY3VybCAtdiAtWCBQT1NUIGh0dHA6Ly8xMjcuMC4wLjE6OTA5MC8tL3JlbG9hZAojCgotIGpvYl9uYW1lOiAiZGVtby1jb25maWciCiAgc2NyYXBlX2ludGVydmFsOiAgICAgMzAwcwogIHN0YXRpY19jb25maWdzOgogIC0gdGFyZ2V0czoKICAgICAgICAgIC0geW91ci1lbmRwb2ludDo4MDg5CiAgICBsYWJlbHM6CiAgICAgICBuYW1lOiBkZW1vLXRlc3QKICAgICAgIGVudmlyb25tZW50OiB0ZXN0Cgo=
kind: Secret
metadata:
  creationTimestamp: null
  name: additional-scrape-configs
  namespace: monitoring
