{
 "title": "Logs by App",
 "description": "Log Viewer Dashboard for Loki",
 "tags": [
  "logs",
  "app",
  "troubleshooting",
  "trouble",
  "fast view",
  "simple",
  "sre"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "app", "label": "App", "query": "label_values(job)" },
   { "name": "search", "label": "1sr String Match", "query": "SERVICE_ORDER_EXECUTION" },
   { "name": "second_search", "label": "2nd String Match", "query": "activitiName" },
   { "name": "third_search", "label": "3rd String Match", "query": "Delete" }
  ]
 },
 "panels": [
  {
   "title": "ALL  Match filters",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"$app\"} |= \"$search\" |= \"$second_search\" |= \"$third_search\" [$__range]) )"
    }
   ]
  },
  {
   "title": "1sr String Match",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"$app\"} |= \"$search\" [$__range]) )"
    }
   ]
  },
  {
   "title": "2nd String Match",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"$app\"} |= \"$second_search\"  [$__range]) )"
    }
   ]
  },
  {
   "title": "3rd String Match",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"$app\"} |= \"$third_search\" [$__range]) )"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 11, "x": 11, "y": 0 },
   "options": {
    "content": "# Is similar to run:\n## kubectl logs pod |grep ${search}"
   },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"$app\"} |= \"$third_search\" [$__range]) )"
    }
   ]
  },
  {
   "type": "logs",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{job=\"$app\"} |= \"$search\" |= \"$second_search\" |= \"$third_search\" | logfmt "
    }
   ]
  }
 ]
}