{
 "title": "AWS Elasticsearch",
 "description": "AWS Elasticsearch dashboard let's you visualize Amazon Elasticsearch cluster health, latency, indexing rate, free storage and more.",
 "tags": [
  "AWSElasticSearch",
  "CloudWatch"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "domainName",
    "label": "DomainName",
    "query": "dimension_values($region, AWS/ES, ClusterStatus.green, DomainName)\t"
   },
   {
    "name": "clientId",
    "label": "ClientId",
    "query": "dimension_values($region, AWS/ES, ClusterStatus.green, ClientId)"
   }
  ]
 },
 "panels": [
  { "title": "Overall Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Status",
   "type": "graph",
   "description": "Indicates shard allocation status.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Green",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "ClusterStatus.green",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "Yellow",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "ClusterStatus.yellow",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "Red",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "ClusterStatus.red",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "Cluster Writes Status",
   "type": "graph",
   "description": "Indicates whether the cluster is accepting or blocking write requests. If your cluster is blocking write requests, check storage space, JVM memory pressure and CPU utilization.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "alias": "Green", "expression": "(m3*(-1))+1", "region": "$region", "statistics": [ "Average" ] },
    { "alias": "Red", "expression": "m3*2", "region": "$region", "statistics": [ "Average" ] }
   ]
  },
  {
   "title": "Master instance connection status",
   "type": "graph",
   "description": "Indicates where data nodes can reach the master node. Failures are usually the result of a network connectivity problem.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "alias": "Green", "expression": "m3", "region": "$region", "statistics": [ "Average" ] },
    { "alias": "Red", "expression": "(m3*(-2))+2", "region": "$region", "statistics": [ "Average" ] }
   ]
  },
  {
   "title": "Snapshot failure status",
   "type": "graph",
   "description": "Failure indicate that no automated snapshot has succeeded in the past 36 hours.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "alias": "Green", "expression": "(m3*(-1))+1", "region": "$region", "statistics": [ "Average" ] },
    { "alias": "Red", "expression": "m3*2", "region": "$region", "statistics": [ "Average" ] }
   ]
  },
  {
   "title": "Total nodes",
   "type": "graph",
   "description": "The total number of nodes for your cluster. This metric can increase (often doubling) during configuration changes and service software updates.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "Nodes",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Minimum" ]
    }
   ]
  },
  {
   "title": "Total free storage space",
   "type": "graph",
   "description": "The total amount of free storage space, accross all data nodes.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Kibana Status",
   "type": "graph",
   "description": "Green indicates normal behavior. Yellow indicates some Kibana instances are unhealthy. red indicates Kibana is inaccessible. In most cases, the health of Kibana mirrors the of the cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "alias": "Green", "expression": "FLOOR(m3)", "region": "$region", "statistics": [ "Average" ] },
    { "alias": "Yellow", "expression": "CEIL(ABS(ABS((m3*2)-1)-1))*2", "region": "$region", "statistics": [ "Average" ] },
    { "alias": "Red", "expression": "(CEIL(m3)*(-3))+3", "region": "$region", "statistics": [ "Average" ] }
   ]
  },
  {
   "title": "Deleted Documents",
   "type": "graph",
   "description": "The total number of documents marked for deletion across all indices in the cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "DeletedDocuments",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Searchable documents",
   "type": "graph",
   "description": "The total number of searchable documents across all indices in the cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "SearchableDocuments",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "Key Performance indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Indexing Rate",
   "type": "graph",
   "description": "The number of indexing operations per minute. For example, a single call to the _bulk API that adds two documents and updates two counts as four operations plus four additional operations per replica. Document deletions do not towards this metric.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Operations/min" }
   ],
   "targets": [
    {
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "IndexingRate",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "SearchRate",
   "type": "graph",
   "description": "The number of search operations per minute for all shards in the cluster. For example, a single call to the _search API that returns results from five shards counts as five operations.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Operations/min" }
   ],
   "targets": [
    {
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "SearchRate",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Indexing Latency",
   "type": "graph",
   "description": "The average time that it takes a shard to complete an indexing operation.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "IndexingLatency",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Search Latency",
   "type": "graph",
   "description": "The average time that it takes a shard to complete a search  operation.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "SearchLatency",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "HTTP Requests by Response code",
   "type": "graph",
   "description": "The number of requests to a domain, aggregated by HTTP response code (2xx, 3xx, 4xx, 5xx).",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "2XX",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "2xx",
     "namespace": "AWS/ES",
     "period": "1m",
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "3XX",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "3xx",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "4XX",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "4xx",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "5XX",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "5xx",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Invalid Host Header Requests",
   "type": "graph",
   "description": "The total number of HTTP requests and the number of requests that included and invalid (or missing) host header. Valid requests include the domain endpoint as the host header. ",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "ElasticSearchRequests",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "ElasticsearchRequests",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "InvalidHostHeaderRequests",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "InvalidHostHeaderRequests",
     "namespace": "AWS/ES",
     "period": "1m",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  { "title": "Elasticsearch JVM Thread Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Write Thread Pool",
   "type": "graph",
   "description": "Metrics for the write thread pool: number of threads, tasks in the queue and rejected tasks. If the queue size is consistently high or rejected count is high, consider scaling your cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "ThreadCount",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "ThreadpoolWriteThreads",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "Queue Depth",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "ThreadpoolWriteQueue",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "Rejected Count",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "ThreadpoolWriteRejected",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "Index Thread Pool",
   "type": "graph",
   "description": "Metrics for the index thread pool: number of threads tasks in the queue and rejected tasks. If the queue size is consistently high or rejected count is high, consider scaling your cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "ThreadCount",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "ThreadpoolIndexThreads",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "Queue Depth",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "ThreadpoolIndexQueue",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "Rejected Count",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "ThreadpoolIndexRejected",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "Search Thread Pool",
   "type": "graph",
   "description": "Metrics for search thread pool: number of threads tasks in the queue and rejected tasks. If the queue size is consistently high or rejected count is high, consider scaling your cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "ThreadCount",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "ThreadpoolSearchThreads",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "Queue Depth",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "ThreadpoolSearchQueue",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "Rejected Count",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "ThreadpoolSearchRejected",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "Merge Thread Pool",
   "type": "graph",
   "description": "Metrics for the force merge thread pool: number of threads tasks in the queue and rejected tasks. If the queue size is consistently high or rejected count is high, consider scaling your cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "ThreadCount",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "ThreadpoolForce_mergeThreads",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "Queue Depth",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "ThreadpoolForce_mergeQueue",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "Rejected Count",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "ThreadpoolForce_mergeRejected",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  { "title": "Data Instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Maximum CPU Utilization ",
   "type": "graph",
   "description": "Maximum CPU utilization percentage for all data nodes.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPUUtilization",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "Maximum JVMMemoryPressure",
   "type": "graph",
   "description": "Maximum JVM memory pressure percentage for all data nodes.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "JVMMemoryPressure",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "JVMMemoryPressure",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "Minimum free storage space",
   "type": "graph",
   "description": "The amount of free storage space on the data node with the smallest amount of free storage space in the cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/ES",
     "period": "1m",
     "region": "$region",
     "statistics": [ "Minimum" ]
    }
   ]
  },
  {
   "title": "Maximum Memory Utilization",
   "type": "graph",
   "description": "Maximum memory usage percentage for all data nodes.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "SysMemoryUtilization",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "SysMemoryUtilization",
     "namespace": "AWS/ES",
     "period": "1m",
     "region": "$region",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "ElasticSearch JVM garbage collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }
  },
  {
   "title": "Young collection",
   "type": "graph",
   "description": "The number of times that \"Young generation\" garbage collection has run. A large number if runs is a normal part of cluster operations. ",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "JVMGCYoungCollectionCount",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "JVMGCYoungCollectionCount",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "Young Collection Time",
   "type": "graph",
   "description": "The amount of time, in milliseconds that the cluster has spent performing \"Young generation\" garbage collection.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "JVMGCYoungCollectionTime",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "JVMGCYoungCollectionTime",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "Old collection",
   "type": "graph",
   "description": "The  number of times that \"old generation\" garbage collection has run. In a cluster with sufficient resources this number should remain small.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "JVMGCOldCollectionCount",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "JVMGCOldCollectionCount",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "Old Collection Time",
   "type": "graph",
   "description": "The amount of time, in milliseconds that the cluster has spent performing \"old generation\" garbage collection.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "JVMGCOldCollectionTime",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "JVMGCOldCollectionTime",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  { "title": "Dedicated master instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "description": "CPU utilization percentage for the master node.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "MasterCPUUtilization",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "MasterCPUUtilization",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "JVMMemoryPressure",
   "type": "graph",
   "description": "JVM memory pressure percentage for the master node.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "MasterJVMMemoryPressure",
     "dimensions": { "ClientId": "$clientId", "DomainName": "$domainName" },
     "metricName": "MasterJVMMemoryPressure",
     "namespace": "AWS/ES",
     "region": "$region",
     "statistics": [ "Maximum" ]
    }
   ]
  }
 ]
}