apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 8.3.4
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: grafana
      app.kubernetes.io/name: grafana
      app.kubernetes.io/part-of: kube-prometheus
  template:
    metadata:
      annotations:
        checksum/grafana-datasources: 94437af43b4bb589dd53fbb6ce41aa2b
      labels:
        app.kubernetes.io/component: grafana
        app.kubernetes.io/name: grafana
        app.kubernetes.io/part-of: kube-prometheus
        app.kubernetes.io/version: 8.3.4
    spec:
      containers:
      - env: 
        - name: GF_AUTH_BASIC_ENABLED
          value: "true"
        - name: GF_SECURITY_ADMIN_USER
          value: "admin"
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "SuperPowerPassword"         
        - name: GF_INSTALL_PLUGINS
          value: "grafana-googlesheets-datasource,agenty-flowcharting-panel,cloudspout-button-panel,jdbranham-diagram-panel,grafana-polystat-panel,novatec-sdg-panel,vonage-status-panel,gretamosa-topology-panel,smartmakers-trafficlight-panel,snuids-trafficlights-panel,grafana-piechart-panel,grafana-opensearch-datasource,yesoreyeram-infinity-datasource,innius-video-panel"
        image: grafana/grafana:8.4.3  # Log4Shell CVE not detected
        name: grafana
        ports:
        - containerPort: 3000
          name: http
        readinessProbe:
          httpGet:
            path: /api/health
            port: http
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-storage
          readOnly: false
        - mountPath: /etc/grafana/provisioning/datasources
          name: grafana-all-datasources
          readOnly: false
        - mountPath: /etc/grafana/provisioning/dashboards
          name: grafana-dashboards
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/alertmanager-overview
          name: grafana-dashboard-alertmanager-overview
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/apiserver
          name: grafana-dashboard-apiserver
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/cluster-total
          name: grafana-dashboard-cluster-total
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/controller-manager
          name: grafana-dashboard-controller-manager
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/k8s-resources-cluster
          name: grafana-dashboard-k8s-resources-cluster
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/k8s-resources-namespace
          name: grafana-dashboard-k8s-resources-namespace
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/k8s-resources-node
          name: grafana-dashboard-k8s-resources-node
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/k8s-resources-pod
          name: grafana-dashboard-k8s-resources-pod
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/k8s-resources-workload
          name: grafana-dashboard-k8s-resources-workload
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/k8s-resources-workloads-namespace
          name: grafana-dashboard-k8s-resources-workloads-namespace
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/kubelet
          name: grafana-dashboard-kubelet
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/namespace-by-pod
          name: grafana-dashboard-namespace-by-pod
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/namespace-by-workload
          name: grafana-dashboard-namespace-by-workload
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/node-cluster-rsrc-use
          name: grafana-dashboard-node-cluster-rsrc-use
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/node-rsrc-use
          name: grafana-dashboard-node-rsrc-use
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/nodes
          name: grafana-dashboard-nodes
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/persistentvolumesusage
          name: grafana-dashboard-persistentvolumesusage
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/pod-total
          name: grafana-dashboard-pod-total
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/prometheus-remote-write
          name: grafana-dashboard-prometheus-remote-write
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/prometheus
          name: grafana-dashboard-prometheus
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/proxy
          name: grafana-dashboard-proxy
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/scheduler
          name: grafana-dashboard-scheduler
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/workload-total
          name: grafana-dashboard-workload-total
        - mountPath: /grafana-dashboard-definitions/0/grafana-dashboard-aws-vpn
          name: grafana-dashboard-aws-vpn
          readOnly: false           
#--------------------------------------------------------------
#---- JPRADO CUSTOM IMPLEMENTATION ----------------------------
#-------------------------------------------------------------- 
        - mountPath: /grafana-dashboard-definitions/0/grafana-dashboard-logs-by-app
          name: grafana-dashboard-logs-by-app
          readOnly: false 
        - mountPath: /grafana-dashboard-definitions/0/aws-cloudwatch-logs
          name: aws-cloudwatch-logs
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/aws-rds
          name: aws-rds
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/aws-ec2
          name: aws-ec2
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/aws-billing-dashboard
          name: aws-billing-dashboard
          readOnly: false       
        - mountPath: /grafana-dashboard-definitions/0/aws-cloudwatch-elasticsearch
          name: aws-cloudwatch-elasticsearch
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/grafana-dashboard-aws-nlb
          name: grafana-dashboard-aws-nlb
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/grafana-dashboard-aws-alb
          name: grafana-dashboard-aws-alb
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/grafana-dashboard-aws-auto-scaling
          name: grafana-dashboard-aws-auto-scaling
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/grafana-dashboard-aws-cert-manager
          name: grafana-dashboard-aws-cert-manager
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/grafana-dashboard-pvc-fast-view
          name: grafana-dashboard-pvc-fast-view
          readOnly: false
        - mountPath: /grafana-dashboard-definitions/0/grafana-dashboard-cluster-fast-overview
          name: grafana-dashboard-cluster-fast-overview
          readOnly: false
#--------------------------------------------------------------          
      nodeSelector:
        #beta.kubernetes.io/os: linux # [beta.kubernetes.io/os]: deprecated since v1.14; use "kubernetes.io/os" instead
        kubernetes.io/os: linux
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: grafana
      volumes:
      - emptyDir: {}
        name: grafana-storage
      - name: grafana-all-datasources
        configMap:
            name: grafana-all-datasources
      - configMap:
          name: grafana-dashboards
        name: grafana-dashboards
      - configMap:
          name: grafana-dashboard-alertmanager-overview
        name: grafana-dashboard-alertmanager-overview
      - configMap:
          name: grafana-dashboard-apiserver
        name: grafana-dashboard-apiserver
      - configMap:
          name: grafana-dashboard-cluster-total
        name: grafana-dashboard-cluster-total
      - configMap:
          name: grafana-dashboard-controller-manager
        name: grafana-dashboard-controller-manager
      - configMap:
          name: grafana-dashboard-k8s-resources-cluster
        name: grafana-dashboard-k8s-resources-cluster
      - configMap:
          name: grafana-dashboard-k8s-resources-namespace
        name: grafana-dashboard-k8s-resources-namespace
      - configMap:
          name: grafana-dashboard-k8s-resources-node
        name: grafana-dashboard-k8s-resources-node
      - configMap:
          name: grafana-dashboard-k8s-resources-pod
        name: grafana-dashboard-k8s-resources-pod
      - configMap:
          name: grafana-dashboard-k8s-resources-workload
        name: grafana-dashboard-k8s-resources-workload
      - configMap:
          name: grafana-dashboard-k8s-resources-workloads-namespace
        name: grafana-dashboard-k8s-resources-workloads-namespace
      - configMap:
          name: grafana-dashboard-kubelet
        name: grafana-dashboard-kubelet
      - configMap:
          name: grafana-dashboard-namespace-by-pod
        name: grafana-dashboard-namespace-by-pod
      - configMap:
          name: grafana-dashboard-namespace-by-workload
        name: grafana-dashboard-namespace-by-workload
      - configMap:
          name: grafana-dashboard-node-cluster-rsrc-use
        name: grafana-dashboard-node-cluster-rsrc-use
      - configMap:
          name: grafana-dashboard-node-rsrc-use
        name: grafana-dashboard-node-rsrc-use
      - configMap:
          name: grafana-dashboard-nodes
        name: grafana-dashboard-nodes
      - configMap:
          name: grafana-dashboard-persistentvolumesusage
        name: grafana-dashboard-persistentvolumesusage
      - configMap:
          name: grafana-dashboard-pod-total
        name: grafana-dashboard-pod-total
      - configMap:
          name: grafana-dashboard-prometheus-remote-write
        name: grafana-dashboard-prometheus-remote-write
      - configMap:
          name: grafana-dashboard-prometheus
        name: grafana-dashboard-prometheus
      - configMap:
          name: grafana-dashboard-proxy
        name: grafana-dashboard-proxy
      - configMap:
          name: grafana-dashboard-scheduler
        name: grafana-dashboard-scheduler
      - configMap:
          name: grafana-dashboard-workload-total
        name: grafana-dashboard-workload-total
      - configMap:
          name: grafana-dashboard-aws-vpn
        name: grafana-dashboard-aws-vpn
#--------------------------------------------------------------
#--------- JPRADO CUSTOM IMPLEMENTATION -----------------------
#--------------------------------------------------------------
      - configMap:
          name: grafana-dashboard-logs-by-app
        name: grafana-dashboard-logs-by-app
      - configMap:
          name: aws-cloudwatch-logs
        name: aws-cloudwatch-logs
      - configMap:
          name: aws-rds
        name: aws-rds
      - configMap:
          name: aws-ec2
        name: aws-ec2
      - configMap:
          name: aws-billing-dashboard
        name: aws-billing-dashboard
      - configMap:
          name: aws-cloudwatch-elasticsearch
        name: aws-cloudwatch-elasticsearch
      - configMap:
          name: grafana-dashboard-aws-nlb
        name: grafana-dashboard-aws-nlb
      - configMap:
          name: grafana-dashboard-aws-alb
        name: grafana-dashboard-aws-alb
      - configMap:
          name: grafana-dashboard-aws-auto-scaling
        name: grafana-dashboard-aws-auto-scaling
      - configMap:
          name: grafana-dashboard-aws-cert-manager
        name: grafana-dashboard-aws-cert-manager
      - configMap:
          name: grafana-dashboard-pvc-fast-view
        name: grafana-dashboard-pvc-fast-view
      - configMap:
          name: grafana-dashboard-cluster-fast-overview
        name: grafana-dashboard-cluster-fast-overview
